/**
 * This class is generated by jOOQ
 */
package info.gngr.db;

/**
 * A class modelling foreign key relationships between tables of the
 * <code>PUBLIC</code> schema
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

  // -------------------------------------------------------------------------
  // IDENTITY definitions
  // -------------------------------------------------------------------------

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final org.jooq.UniqueKey<info.gngr.db.tables.records.PermissionsRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;
  public static final org.jooq.UniqueKey<info.gngr.db.tables.records.CookiesRecord> CONSTRAINT_6 = UniqueKeys0.CONSTRAINT_6;
  public static final org.jooq.UniqueKey<info.gngr.db.tables.records.GlobalsRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
    public static final org.jooq.UniqueKey<info.gngr.db.tables.records.PermissionsRecord> CONSTRAINT_C = createUniqueKey(
        info.gngr.db.tables.Permissions.PERMISSIONS, info.gngr.db.tables.Permissions.PERMISSIONS.FRAMEHOST,
        info.gngr.db.tables.Permissions.PERMISSIONS.REQUESTHOST);
    public static final org.jooq.UniqueKey<info.gngr.db.tables.records.CookiesRecord> CONSTRAINT_6 = createUniqueKey(
        info.gngr.db.tables.Cookies.COOKIES, info.gngr.db.tables.Cookies.COOKIES.HOSTNAME, info.gngr.db.tables.Cookies.COOKIES.NAME);
    public static final org.jooq.UniqueKey<info.gngr.db.tables.records.GlobalsRecord> CONSTRAINT_3 = createUniqueKey(
        info.gngr.db.tables.Globals.GLOBALS, info.gngr.db.tables.Globals.GLOBALS.NOTACOLUMN);
  }
}
