/**
 * This class is generated by jOOQ
 */
package info.gngr.db;

/**
 * Convenience access to all tables in PUBLIC
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

  /**
   * The table PUBLIC.PERMISSIONS
   */
  public static final info.gngr.db.tables.Permissions PERMISSIONS = info.gngr.db.tables.Permissions.PERMISSIONS;

  /**
   * The table PUBLIC.COOKIES
   */
  public static final info.gngr.db.tables.Cookies COOKIES = info.gngr.db.tables.Cookies.COOKIES;

  /**
   * The table PUBLIC.GLOBALS
   */
  public static final info.gngr.db.tables.Globals GLOBALS = info.gngr.db.tables.Globals.GLOBALS;
}
