/**
 * This class is generated by jOOQ
 */
package info.gngr.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CookiesRecord extends org.jooq.impl.UpdatableRecordImpl<info.gngr.db.tables.records.CookiesRecord>
    implements
    org.jooq.Record8<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Long, java.lang.Long> {

  private static final long serialVersionUID = -1249579634;

  /**
   * Setter for <code>PUBLIC.COOKIES.HOSTNAME</code>.
   */
  public void setHostname(final java.lang.String value) {
    setValue(0, value);
  }

  /**
   * Getter for <code>PUBLIC.COOKIES.HOSTNAME</code>.
   */
  public java.lang.String getHostname() {
    return (java.lang.String) getValue(0);
  }

  /**
   * Setter for <code>PUBLIC.COOKIES.NAME</code>.
   */
  public void setName(final java.lang.String value) {
    setValue(1, value);
  }

  /**
   * Getter for <code>PUBLIC.COOKIES.NAME</code>.
   */
  public java.lang.String getName() {
    return (java.lang.String) getValue(1);
  }

  /**
   * Setter for <code>PUBLIC.COOKIES.VALUE</code>.
   */
  public void setValue(final java.lang.String value) {
    setValue(2, value);
  }

  /**
   * Getter for <code>PUBLIC.COOKIES.VALUE</code>.
   */
  public java.lang.String getValue() {
    return (java.lang.String) getValue(2);
  }

  /**
   * Setter for <code>PUBLIC.COOKIES.PATH</code>.
   */
  public void setPath(final java.lang.String value) {
    setValue(3, value);
  }

  /**
   * Getter for <code>PUBLIC.COOKIES.PATH</code>.
   */
  public java.lang.String getPath() {
    return (java.lang.String) getValue(3);
  }

  /**
   * Setter for <code>PUBLIC.COOKIES.SECURE</code>.
   */
  public void setSecure(final java.lang.Boolean value) {
    setValue(4, value);
  }

  /**
   * Getter for <code>PUBLIC.COOKIES.SECURE</code>.
   */
  public java.lang.Boolean getSecure() {
    return (java.lang.Boolean) getValue(4);
  }

  /**
   * Setter for <code>PUBLIC.COOKIES.HTTPONLY</code>.
   */
  public void setHttponly(final java.lang.Boolean value) {
    setValue(5, value);
  }

  /**
   * Getter for <code>PUBLIC.COOKIES.HTTPONLY</code>.
   */
  public java.lang.Boolean getHttponly() {
    return (java.lang.Boolean) getValue(5);
  }

  /**
   * Setter for <code>PUBLIC.COOKIES.CREATIONTIME</code>.
   */
  public void setCreationtime(final java.lang.Long value) {
    setValue(6, value);
  }

  /**
   * Getter for <code>PUBLIC.COOKIES.CREATIONTIME</code>.
   */
  public java.lang.Long getCreationtime() {
    return (java.lang.Long) getValue(6);
  }

  /**
   * Setter for <code>PUBLIC.COOKIES.EXPIRATIONTIME</code>.
   */
  public void setExpirationtime(final java.lang.Long value) {
    setValue(7, value);
  }

  /**
   * Getter for <code>PUBLIC.COOKIES.EXPIRATIONTIME</code>.
   */
  public java.lang.Long getExpirationtime() {
    return (java.lang.Long) getValue(7);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public org.jooq.Record2<java.lang.String, java.lang.String> key() {
    return (org.jooq.Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record8 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public org.jooq.Row8<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Long, java.lang.Long> fieldsRow() {
    return (org.jooq.Row8) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public org.jooq.Row8<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Long, java.lang.Long> valuesRow() {
    return (org.jooq.Row8) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public org.jooq.Field<java.lang.String> field1() {
    return info.gngr.db.tables.Cookies.COOKIES.HOSTNAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public org.jooq.Field<java.lang.String> field2() {
    return info.gngr.db.tables.Cookies.COOKIES.NAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public org.jooq.Field<java.lang.String> field3() {
    return info.gngr.db.tables.Cookies.COOKIES.VALUE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public org.jooq.Field<java.lang.String> field4() {
    return info.gngr.db.tables.Cookies.COOKIES.PATH;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public org.jooq.Field<java.lang.Boolean> field5() {
    return info.gngr.db.tables.Cookies.COOKIES.SECURE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public org.jooq.Field<java.lang.Boolean> field6() {
    return info.gngr.db.tables.Cookies.COOKIES.HTTPONLY;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public org.jooq.Field<java.lang.Long> field7() {
    return info.gngr.db.tables.Cookies.COOKIES.CREATIONTIME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public org.jooq.Field<java.lang.Long> field8() {
    return info.gngr.db.tables.Cookies.COOKIES.EXPIRATIONTIME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public java.lang.String value1() {
    return getHostname();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public java.lang.String value2() {
    return getName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public java.lang.String value3() {
    return getValue();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public java.lang.String value4() {
    return getPath();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public java.lang.Boolean value5() {
    return getSecure();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public java.lang.Boolean value6() {
    return getHttponly();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public java.lang.Long value7() {
    return getCreationtime();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public java.lang.Long value8() {
    return getExpirationtime();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public CookiesRecord value1(final java.lang.String value) {
    setHostname(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public CookiesRecord value2(final java.lang.String value) {
    setName(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public CookiesRecord value3(final java.lang.String value) {
    setValue(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public CookiesRecord value4(final java.lang.String value) {
    setPath(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public CookiesRecord value5(final java.lang.Boolean value) {
    setSecure(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public CookiesRecord value6(final java.lang.Boolean value) {
    setHttponly(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public CookiesRecord value7(final java.lang.Long value) {
    setCreationtime(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public CookiesRecord value8(final java.lang.Long value) {
    setExpirationtime(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public CookiesRecord values(final java.lang.String value1, final java.lang.String value2, final java.lang.String value3,
      final java.lang.String value4, final java.lang.Boolean value5, final java.lang.Boolean value6, final java.lang.Long value7,
      final java.lang.Long value8) {
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached CookiesRecord
   */
  public CookiesRecord() {
    super(info.gngr.db.tables.Cookies.COOKIES);
  }

  /**
   * Create a detached, initialised CookiesRecord
   */
  public CookiesRecord(final java.lang.String hostname, final java.lang.String name, final java.lang.String value,
      final java.lang.String path, final java.lang.Boolean secure, final java.lang.Boolean httponly, final java.lang.Long creationtime,
      final java.lang.Long expirationtime) {
    super(info.gngr.db.tables.Cookies.COOKIES);

    setValue(0, hostname);
    setValue(1, name);
    setValue(2, value);
    setValue(3, path);
    setValue(4, secure);
    setValue(5, httponly);
    setValue(6, creationtime);
    setValue(7, expirationtime);
  }
}
